### ISSUE TITLE
npm test 报错？

### ISSUE THREAD

**Issue by nobodxbodon** [OrangeX4/Orangex#1]
`npm install` 后运行:
```
$ npm test

> orangex@1.0.2 test /Users/xuanwu/git/Orangex/nodejs
> npm run build && node dist/main && 橙式 测试 && cd src && cd 测试 && 橙式 英转汉


> orangex@1.0.2 build /Users/xuanwu/git/Orangex/nodejs
> webpack --progress --env.development

Hash: b7358e7d55417f913fcc
Version: webpack 4.41.5
Time: 4995ms
Built at: 02/12/2020 9:32:54 AM
  Asset      Size  Chunks             Chunk Names
main.js  1.83 MiB    main  [emitted]  main
Entrypoint main = main.js
[0] multi ./src/index.ts 28 bytes {main} [built]
[./src/index.ts] 3.21 KiB {main} [built]
[./src/lib/fileReplacer.ts] 8.08 KiB {main} [built]
[./src/lib/replacer.ts] 3.11 KiB {main} [built]
[./src/lib/utils.ts] 3.34 KiB {main} [built]
[./src/test/main.test.ts] 764 bytes {main} [built]
[buffer] external "buffer" 42 bytes {main} [built]
[child_process] external "child_process" 42 bytes {main} [built]
[fs] external "fs" 42 bytes {main} [built]
[http] external "http" 42 bytes {main} [built]
[https] external "https" 42 bytes {main} [built]
[os] external "os" 42 bytes {main} [built]
[path] external "path" 42 bytes {main} [built]
[stream] external "stream" 42 bytes {main} [built]
[url] external "url" 42 bytes {main} [built]
    + 68 hidden modules
undefined:35
        catch {
              ^

SyntaxError: Unexpected token {
    at Object../src/lib/fileReplacer.ts (/Users/xuanwu/git/Orangex/nodejs/dist/main.js:850:1)
    at __webpack_require__ (/Users/xuanwu/git/Orangex/nodejs/dist/main.js:20:30)
    at eval (webpack-internal:///./src/index.ts:15:75)
    at Module../src/index.ts (/Users/xuanwu/git/Orangex/nodejs/dist/main.js:838:1)
    at __webpack_require__ (/Users/xuanwu/git/Orangex/nodejs/dist/main.js:20:30)
    at Object.0 (/Users/xuanwu/git/Orangex/nodejs/dist/main.js:897:18)
    at __webpack_require__ (/Users/xuanwu/git/Orangex/nodejs/dist/main.js:20:30)
    at /Users/xuanwu/git/Orangex/nodejs/dist/main.js:84:18
    at Object.<anonymous> (/Users/xuanwu/git/Orangex/nodejs/dist/main.js:87:10)
    at Module._compile (module.js:624:30)
npm ERR! Test failed.  See above for more details.
```

PS: 多谢投稿！

**Comment by nobodxbodon** [comment]
npm start 也同样：
```
[nodemon] 2.0.2
[nodemon] to restart at any time, enter `rs`
[nodemon] watching dir(s): dist/main.js
[nodemon] watching extensions: js,mjs,json
[nodemon] starting `node dist/main.js`
undefined:35
        catch {
              ^

SyntaxError: Unexpected token {
    at Object../src/lib/fileReplacer.ts (/Users/xuanwu/git/Orangex/nodejs/dist/main.js:850:1)
    at __webpack_require__ (/Users/xuanwu/git/Orangex/nodejs/dist/main.js:20:30)
    at eval (webpack-internal:///./src/index.ts:15:75)
    at Module../src/index.ts (/Users/xuanwu/git/Orangex/nodejs/dist/main.js:838:1)
    at __webpack_require__ (/Users/xuanwu/git/Orangex/nodejs/dist/main.js:20:30)
    at Object.0 (/Users/xuanwu/git/Orangex/nodejs/dist/main.js:897:18)
    at __webpack_require__ (/Users/xuanwu/git/Orangex/nodejs/dist/main.js:20:30)
    at /Users/xuanwu/git/Orangex/nodejs/dist/main.js:84:18
    at Object.<anonymous> (/Users/xuanwu/git/Orangex/nodejs/dist/main.js:87:10)
    at Module._compile (module.js:624:30)
[nodemon] app crashed - waiting for file changes before starting...
```

**Comment by nobodxbodon** [comment]
安装后运行也同样：
```
$ npm install orangex -g  
/usr/local/bin/橙式 -> /usr/local/lib/node_modules/orangex/bin/orangex.js
/usr/local/bin/命令 -> /usr/local/lib/node_modules/orangex/bin/command.js
+ orangex@1.0.1
added 4 packages from 4 contributors in 1.426s

$ 橙式
undefined:35
        catch {
              ^

SyntaxError: Unexpected token {
    at Object../src/lib/fileReplacer.ts (/usr/local/lib/node_modules/orangex/dist/main.js:850:1)
    at __webpack_require__ (/usr/local/lib/node_modules/orangex/dist/main.js:20:30)
    at eval (webpack-internal:///./src/index.ts:15:75)
    at Module../src/index.ts (/usr/local/lib/node_modules/orangex/dist/main.js:838:1)
    at __webpack_require__ (/usr/local/lib/node_modules/orangex/dist/main.js:20:30)
    at Object.0 (/usr/local/lib/node_modules/orangex/dist/main.js:897:18)
    at __webpack_require__ (/usr/local/lib/node_modules/orangex/dist/main.js:20:30)
    at /usr/local/lib/node_modules/orangex/dist/main.js:84:18
    at Object.<anonymous> (/usr/local/lib/node_modules/orangex/dist/main.js:87:10)
    at Module._compile (module.js:624:30)
```

**Comment by nobodxbodon** [comment]
```
$ npm version
{ npm: '6.7.0',
  ares: '1.10.1-DEV',
  cldr: '31.0.1',
  http_parser: '2.7.0',
  icu: '59.1',
  modules: '57',
  nghttp2: '1.25.0',
  node: '8.7.0',
  openssl: '1.0.2l',
  tz: '2017b',
  unicode: '9.0',
  uv: '1.15.0',
  v8: '6.1.534.42',
  zlib: '1.2.11' }
```

**Comment by OrangeX4** [comment]
D:\project\Orangex\nodejs>橙式
使用"橙式 帮助"命令可获取帮助信息:)

D:\project\Orangex\nodejs>npm version
{
  orangex: '1.0.5',
  npm: '6.13.4',
  ares: '1.15.0',
  brotli: '1.0.7',
  cldr: '35.1',
  http_parser: '2.8.0',
  icu: '64.2',
  llhttp: '2.0.1',
  modules: '72',
  napi: '5',
  nghttp2: '1.40.0',
  node: '12.14.1',
  openssl: '1.1.1d',
  tz: '2019c',
  unicode: '12.1',
  uv: '1.33.1',
  v8: '7.7.299.13-node.16',
  zlib: '1.2.11'
}

电脑上npm 6.13.4安装成功，
手机上用termux和npm 6.12.0安装成功,
现在我升级npm到6.7.0试试.

感谢issue : )

**Comment by OrangeX4** [comment]
`D:\project\Orangex\nodejs>橙式
使用"橙式 帮助"命令可获取帮助信息:)

D:\project\Orangex\nodejs>npm version
{
  orangex: '1.0.5',
  npm: '6.7.0',
  ares: '1.15.0',
  brotli: '1.0.7',
  cldr: '35.1',
  http_parser: '2.9.3',
  icu: '64.2',
  llhttp: '2.0.4',
  modules: '72',
  napi: '5',
  nghttp2: '1.40.0',
  node: '12.15.0',
  openssl: '1.1.1d',
  tz: '2019c',
  unicode: '12.1',
  uv: '1.33.1',
  v8: '7.7.299.13-node.16',
  zlib: '1.2.11'
}`
npm 6.7.0 安装成功。
可以尝试重新安装一次试试？
